#############################################################################
# Generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#  Mar 18, 2019 07:54:12 PM MSK  platform: Linux
set vTcl(timestamp) ""


#############################################################################
## vTcl Code to Load User Images see vTcl:save2 in file.tcl

catch {package require Img}

foreach img {

        {{[file join / home senya {Рабочий стол} AlexandraYakovleva проект python img 1.png]} {user image} user {}}

            } {
# from vTcl:image:dump_create_image_footer
    eval set _file [lindex $img 0]
    vTcl:image:create_new_image\
        $_file [lindex $img 1] [lindex $img 2] [lindex $img 3]
}

if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 916x652+611+181
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure PC.TNotebook -background #d9d9d9
    ttk::style configure PC.TNotebook.Tab -background #d9d9d9
    ttk::style configure PC.TNotebook.Tab -foreground #000000
    ttk::style configure PC.TNotebook.Tab -font "TkDefaultFont"
    ttk::style layout PC.TNotebook.Tab {
                    Notebook.tab -children {
                        Notebook.padding -side top -children {
                            Notebook.focus -side top -children {
                                Notebook.text -side right
                                Notebook.image -side left
                            }
                        }
                    }
               }
    vTcl::widgets::ttk::pnotebook::createCmd $top.pNo65 \
        -width 300 -height 200 -style {"PC.TNotebook"} 
    vTcl:DefineAlias "$top.pNo65" "PNotebook1" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo65 configure -style "PC.TNotebook"
    bind $top.pNo65 <Button-1> {
        _button_press
    }
    bind $top.pNo65 <ButtonRelease-1> {
        _button_release
    }
    bind $top.pNo65 <Motion> {
        _mouse_over
    }
    frame $top.pNo65.t0 \
        -background {#ffffff} -highlightbackground {#d8d8d8} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.pNo65.t0" "PNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo65 add $top.pNo65.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image image2 \
        -compound none -underline -1 
    set site_4_0  $top.pNo65.t0
    ttk::label $site_4_0.tLa66 \
        -background {#d9d9d9} -foreground {#000000} -font TkDefaultFont \
        -relief flat -text {} \
        -image [vTcl:image:get_image [file join / home senya {Рабочий стол} AlexandraYakovleva проект python img 1.png]] 
    vTcl:DefineAlias "$site_4_0.tLa66" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {-family {DejaVu Sans} -size 16} \
        -foreground {#000000} -highlightcolor black -text {T =} 
    vTcl:DefineAlias "$site_4_0.lab68" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent69 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent69" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent70 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent70" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {-family {DejaVu Sans} -size 16} \
        -foreground {#000000} -highlightcolor black -text {F =} 
    vTcl:DefineAlias "$site_4_0.lab72" "Label6" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font "TkDefaultFont"
    ttk::button $site_4_0.tBu73 \
        -takefocus {} -text Рассчитать 
    vTcl:DefineAlias "$site_4_0.tBu73" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    canvas $site_4_0.can74 \
        -background {#ffffff} -borderwidth 2 -closeenough 1.0 -height 231 \
        -highlightbackground {#ffffff} -relief ridge \
        -selectbackground {#ffffff} -selectforeground black -width 421 
    vTcl:DefineAlias "$site_4_0.can74" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad43 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text {β/α (max -> min)} \
        -variable {} 
    vTcl:DefineAlias "$site_4_0.rad43" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_4_0.rad44 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text {интеграл θ (max -> min)} \
        -variable {} 
    vTcl:DefineAlias "$site_4_0.rad44" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab45 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -text {Выберите сортировку:} 
    vTcl:DefineAlias "$site_4_0.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab46 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -text Результат: 
    vTcl:DefineAlias "$site_4_0.lab46" "Label2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tLa66 \
        -in $site_4_0 -x 30 -y 20 -width 720 -relwidth 0 -height 239 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab68 \
        -in $site_4_0 -x 50 -y 470 -anchor nw -bordermode ignore 
    place $site_4_0.ent69 \
        -in $site_4_0 -x 110 -y 410 -width 106 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent70 \
        -in $site_4_0 -x 110 -y 460 -width 106 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab72 \
        -in $site_4_0 -x 50 -y 420 -width 42 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tBu73 \
        -in $site_4_0 -x 40 -y 540 -width 170 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.can74 \
        -in $site_4_0 -x 400 -y 320 -width 421 -relwidth 0 -height 231 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad43 \
        -in $site_4_0 -x 40 -y 340 -anchor nw -bordermode ignore 
    place $site_4_0.rad44 \
        -in $site_4_0 -x 40 -y 370 -anchor nw -bordermode ignore 
    place $site_4_0.lab45 \
        -in $site_4_0 -x 40 -y 300 -anchor nw -bordermode ignore 
    place $site_4_0.lab46 \
        -in $site_4_0 -x 400 -y 290 -anchor nw -bordermode ignore 
    frame $top.pNo65.t1 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.pNo65.t1" "PNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.pNo65 add $top.pNo65.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image image2 \
        -compound none -underline -1 
    set site_4_1  $top.pNo65.t1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.pNo65 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}
#############################################################################
## Binding tag:  _vTclBalloon


if {![info exists vTcl(sourcing)]} {
bind "_vTclBalloon" <<KillBalloon>> {
    namespace eval ::vTcl::balloon {
        after cancel $id
        if {[winfo exists .vTcl.balloon]} {
            destroy .vTcl.balloon
        }
        set set 0
    }
}
bind "_vTclBalloon" <<vTclBalloon>> {
    if {$::vTcl::balloon::first != 1} {break}
    namespace eval ::vTcl::balloon {
        set first 2
        if {![winfo exists .vTcl]} {
            toplevel .vTcl; wm withdraw .vTcl
        }
        if {![winfo exists .vTcl.balloon]} {
            toplevel .vTcl.balloon -bg black
        }
        wm overrideredirect .vTcl.balloon 1
        label .vTcl.balloon.l  -text ${%W} -relief flat  -bg #ffffaa -fg black -padx 2 -pady 0 -anchor w
        pack .vTcl.balloon.l -side left -padx 1 -pady 1
        wm geometry  .vTcl.balloon  +[expr {[winfo rootx %W]+[winfo width %W]/2}]+[expr {[winfo rooty %W]+[winfo height %W]+4}]
        set set 1
    }
}
bind "_vTclBalloon" <Button> {
    namespace eval ::vTcl::balloon {
        set first 0
    }
    vTcl:FireEvent %W <<KillBalloon>>
}
bind "_vTclBalloon" <Enter> {
    namespace eval ::vTcl::balloon {
        ## self defining balloon?
        if {![info exists %W]} {
            vTcl:FireEvent %W <<SetBalloon>>
        }
        set set 0
        set first 1
        set id [after 500 {vTcl:FireEvent %W <<vTclBalloon>>}]
    }
}
bind "_vTclBalloon" <Leave> {
    namespace eval ::vTcl::balloon {
        set first 0
    }
    vTcl:FireEvent %W <<KillBalloon>>
}
bind "_vTclBalloon" <Motion> {
    namespace eval ::vTcl::balloon {
        if {!$set} {
            after cancel $id
            set id [after 500 {vTcl:FireEvent %W <<vTclBalloon>>}]
        }
    }
}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

