#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Mar 19, 2019 02:27:57 PM MSK  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
    from tkinter import BooleanVar
    from tkinter import filedialog
try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

from project.python import alexandra_support
from project.python.int_linear_only_lib import integer_lp
from tkinter import messagebox
import os.path


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    print('prog_call = {}'.format(prog_call))
    prog_location = os.path.split(prog_call)[0]
    print('prog_location = {}'.format(prog_location))
    sys.stdout.flush()
    root = tk.Tk()
    top = Toplevel1(root)
    alexandra_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    global prog_location
    prog_call = sys.argv[0]
    print('prog_call = {}'.format(prog_call))
    prog_location = os.path.split(prog_call)[0]
    print('prog_location = {}'.format(prog_location))
    rt = root
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    alexandra_support.init(w, top, *args, **kwargs)
    return w, top


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#ffffff'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#ffffff'  # X11 color: 'gray85'
        _ana2color = '#ffffff'  # Closest X11 color: 'gray92'

        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.', background=_bgcolor)
        self.style.configure('.', foreground=_fgcolor)
        self.style.configure('.', font="TkDefaultFont")
        self.style.map('.', background=
        [('selected', _compcolor), ('active', _ana2color)])

        top.geometry("800x652+611+181")
        top.title("Задачи линейного программирования")
        top.configure(highlightcolor="black")

        self.style.layout("ClosetabNotebook", [("ClosetabNotebook.client",
                                                {"sticky": "nswe"})])
        self.style.layout("ClosetabNotebook.Tab", [
            ("ClosetabNotebook.tab",
             {"sticky": "nswe",
              "children": [
                  ("ClosetabNotebook.padding", {
                      "side": "top",
                      "sticky": "nswe",
                      "children": [
                          ("ClosetabNotebook.focus", {
                              "side": "top",
                              "sticky": "nswe",
                              "children": [
                                  ("ClosetabNotebook.label", {"side":
                                                                  "left", "sticky": ''}),
                                  ("ClosetabNotebook.close", {"side":
                                                                  "left", "sticky": ''}), ]})]})]})])

        PNOTEBOOK = "ClosetabNotebook"

        '''tk variables'''
        self.sort_var = tk.StringVar()
        self.sort_var.set('β/α (max -> min)')
        #  кнопки открытия файла и запуска расчетов
        filename = tk.StringVar()
        filepath = tk.StringVar()
        #  коэффициенты в entry
        F = tk.DoubleVar()
        F.set(100000)
        T = tk.IntVar()
        T.set(30)

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
        [('selected', _compcolor), ('active', _ana2color)])
        self.PNotebook1 = ttk.Notebook(top)
        self.PNotebook1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.PNotebook1.configure(width=300)
        self.PNotebook1.configure(style=PNOTEBOOK)
        self.PNotebook1_t0 = tk.Frame(self.PNotebook1, takefocus='1')
        self.PNotebook1.add(self.PNotebook1_t0, padding=3)
        self.PNotebook1.tab(0, text="Задача 1", compound="none", underline="-1", )
        self.PNotebook1_t0.configure(background="#ffffff")
        self.PNotebook1_t0.configure(highlightbackground="#d8d8d8")
        self.PNotebook1_t1 = tk.Frame(self.PNotebook1)
        self.PNotebook1.add(self.PNotebook1_t1, padding=3)
        self.PNotebook1.tab(1, text="Задача 2", compound="none", underline="-1", )

        self.TLabel2 = ttk.Label(self.PNotebook1_t0)
        self.TLabel2.place(relx=0.038, rely=0.032, height=239, width=720)
        self.TLabel2.configure(background="#d9d9d9")
        self.TLabel2.configure(foreground="#000000")
        self.TLabel2.configure(font="TkDefaultFont")
        self.TLabel2.configure(relief='flat')
        photo_location = os.path.join(prog_location, "./img/1.png")
        self._img0 = tk.PhotoImage(file=photo_location)
        self.TLabel2.configure(image=self._img0)

        self.Label6 = tk.Label(self.PNotebook1_t0)
        self.Label6.place(relx=0.388, rely=0.639, height=30, width=42)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(font="-family {DejaVu Sans} -size 16")
        self.Label6.configure(text='''T =''')

        self.F_entry_p1 = tk.Entry(self.PNotebook1_t0, textvariable=F)
        self.F_entry_p1.place(relx=0.464, rely=0.527, height=43, relwidth=0.133)
        self.F_entry_p1.configure(background="white")
        self.F_entry_p1.configure(font="TkFixedFont")
        self.F_entry_p1.configure(selectbackground="#c4c4c4")

        self.T_entry_p1 = tk.Entry(self.PNotebook1_t0, textvariable=T)
        self.T_entry_p1.place(relx=0.464, rely=0.623, height=43, relwidth=0.133)
        self.T_entry_p1.configure(background="white")
        self.T_entry_p1.configure(font="TkFixedFont")
        self.T_entry_p1.configure(selectbackground="#c4c4c4")

        self.Label6 = tk.Label(self.PNotebook1_t0)
        self.Label6.place(relx=0.388, rely=0.543, height=30, width=42)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(font="-family {DejaVu Sans} -size 16")
        self.Label6.configure(text='''F =''')

        self.radio_sort_ba_p1 = tk.Radiobutton(self.PNotebook1_t0)
        self.radio_sort_ba_p1.place(relx=0.05, rely=0.543, relheight=0.037
                                    , relwidth=0.182)
        self.radio_sort_ba_p1.configure(justify='left')
        self.radio_sort_ba_p1.configure(text='β/α (max -> min)')
        self.radio_sort_ba_p1.configure(variable=self.sort_var, value='β/α (max -> min)')

        self.radio_sort_teta_p1 = tk.Radiobutton(self.PNotebook1_t0)
        self.radio_sort_teta_p1.place(relx=0.05, rely=0.591, relheight=0.037
                                      , relwidth=0.252)
        self.radio_sort_teta_p1.configure(justify='left')
        self.radio_sort_teta_p1.configure(text='интеграл θ (max -> min)')
        self.radio_sort_teta_p1.configure(variable=self.sort_var, value='интеграл θ (max -> min)')

        self.Label1 = tk.Label(self.PNotebook1_t0)
        self.Label1.place(relx=0.05, rely=0.479, height=21, width=180)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Выберите сортировку:''')

        self.Label2 = tk.Label(self.PNotebook1_t0)
        self.Label2.place(relx=0.375, rely=0.479, height=21, width=195)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''Введите коэффициенты:''')

        self.Label3 = tk.Label(self.PNotebook1_t0)
        self.Label3.place(relx=0.705, rely=0.479, height=21, width=185)
        self.Label3.configure(text='''Выберите файл excel:''')

        def open_file():
            file = filedialog.askopenfilename(filetypes=(('excel file', '*.xls'), ('excel file', '*.xlsx'),
                                                         ('excel file', '*.xlsm')))
            if file is not None:
                filename.set(file.rpartition('/')[2])
                filepath.set(file)

        def call_linear_prog(filepath):
            if filepath == '':
                messagebox.showinfo('Ошибка', 'Вы не выбрали файл')
            else:
                T = self.T_entry_p1.get()
                F = self.F_entry_p1.get()
                if T == '' or F == '':
                    messagebox.showinfo('Ошибка', 'Введены не все коэффициенты')
                else:
                    results = integer_lp(filepath, T=T, F=F, sort=self.sort_var.get())
                    messagebox.showinfo('Решение', "\n".join(results))

        self.file_button_p1 = tk.Button(self.PNotebook1_t0, command=open_file)
        self.file_button_p1.place(relx=0.702, rely=0.543, height=41, width=191)
        self.file_button_p1.configure(width=191)
        self.file_button_p1.configure(background="#ffffff")
        self.file_button_p1.configure(relief='sunken', textvariable=filename)

        self.exe_button_p1 = ttk.Button(self.PNotebook1_t0)
        self.exe_button_p1.configure(command=lambda: call_linear_prog(filepath.get()))
        self.exe_button_p1.place(relx=0.330, rely=0.790, height=70, width=250)
        self.exe_button_p1.configure(text='''Рассчитать''')

        self.PNotebook1.bind('<Button-1>', _button_press)
        self.PNotebook1.bind('<ButtonRelease-1>', _button_release)
        self.PNotebook1.bind('<Motion>', _mouse_over)


# The following code is add to handle mouse events with the close icons
# in PNotebooks widgets.
def _button_press(event):
    widget = event.widget
    element = widget.identify(event.x, event.y)
    if "close" in element:
        index = widget.index("@%d,%d" % (event.x, event.y))
        widget.state(['pressed'])
        widget._active = index


def _button_release(event):
    widget = event.widget
    if not widget.instate(['pressed']):
        return
    element = widget.identify(event.x, event.y)
    try:
        index = widget.index("@%d,%d" % (event.x, event.y))
    except TclError:
        pass
    if "close" in element and widget._active == index:
        widget.forget(index)
        widget.event_generate("<<NotebookTabClosed>>")

    widget.state(['!pressed'])
    widget._active = None


def _mouse_over(event):
    widget = event.widget
    element = widget.identify(event.x, event.y)
    if "close" in element:
        widget.state(['alternate'])
    else:
        widget.state(['!alternate'])


if __name__ == '__main__':
    vp_start_gui()
